name: Daily Test

on:
  schedule:
    # More information on cron https://crontab.guru/
    # GitHub actions is using UTC time. Scheduling action at 3 am PST
    - cron: '0 11 * * *'

  workflow_dispatch:

# note secrets can only be referenced in env or run
env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  DEMO_APP_DOWNLOAD_LINK: ${{ secrets.DEMO_APP_DOWNLOAD_LINK }}
  DEMO_APP_DOWNLOAD_LINK_NO_VIDEO_CODECS: ${{ secrets.DEMO_APP_DOWNLOAD_LINK_NO_VIDEO_CODECS }}

jobs:
  daily-test:
    name: Amazon Chime Android SDK Daily Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest 2 Android versions. TODO: Upgrade to Appium 2 for OS 14 and above.
        os_list: ["12", "13"]
        demo_download_url_list: ["$DEMO_APP_DOWNLOAD_LINK", "$DEMO_APP_DOWNLOAD_LINK_NO_VIDEO_CODECS"]
    outputs:
      job-status: ${{ job.status }}

    steps:
      - name: Checkout test package
        uses: actions/checkout@v4
        with:
          repository: awslabs/amazon-chime-sdk-apple
          token: ${{ secrets.GH_INTEG_READ_ONLY_PAT }}
          ref: automated-test-development

      - name: Get latest prod demo app
        run: |
          wget -O amazon-chime-sdk-app.apk ${{ matrix.demo_download_url_list }}

      - name: Setup Node.js - 15.x
        uses: actions/setup-node@v4
        with:
          node-version: 15.x

      - name: Run tests against specified Android versions
        id: tests
        run: |
          id=$(curl -F 'payload=@amazon-chime-sdk-app.apk' -F name=amazon-chime-sdk-app.apk -u "${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }}" 'https://api.us-west-1.saucelabs.com/v1/storage/upload' |jq '.item.id')
          npm install
          npm run build
          npm run cma -- --app-url "sample.apk" --log-level error --tag "@common" --app-id "${id}" --retry --platform-version ${{ matrix.os_list }}

      - name: Send Notification
        uses: slackapi/slack-github-action@v1.25.0
        if: failure()
        with:
          payload: |
            {
              "Platform": "Android",
              "Link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "Status": "${{ steps.tests.outcome }}"
            }
